### ISSUE TITLE
NoMethodError on require

### ISSUE THREAD

**Issue by tylerhunt** [rom-rb/rom-yesql#1]
I'm seeing the following error when simply loading the library:

```
>> require 'rom'
=> true
>> require 'rom-yesql'
NoMethodError: undefined method `defines' for ROM::Yesql::Relation:Class
    from /[…]/.bundle/gems/rom-yesql-0.0.1/lib/rom/yesql/relation.rb:27:in `<class:Relation>'
```

This appears to be due to [this line](http://git.io/hiha) in `ROM::Relation::ClassInterface`:

``` ruby
return if klass.superclass == ROM::Relation
```

Since it's returning early, it's never extended with the `ROM::ClassMacros` like it should be.

**Comment by solnic** [comment]
Sorry about that. Did not have the time to update yesql yet. I'll fix it

**Comment by solnic** [comment]
OK I fixed it. I'm gonna push one more alpha 0.0.2 and then 0.1.0 along with final ROM 0.6.0 :)

**Comment by tylerhunt** [comment]
Sweet, thanks!
