### ISSUE TITLE
undefined method 'name' for ROM::Yesql::Relation

### ISSUE THREAD

**Issue by mrship** [rom-rb/rom-yesql#11]
I'm trying to use a rom-yesql relation with a rom repository. However, I get an error when I try to call `.to_a` on the relation from within the repository.

The error is thrown from [within rom-repository](https://github.com/rom-rb/rom-repository/blob/master/lib/rom/repository/relation_proxy.rb#L40) where it is expecting the relation to have a method `name`. The `Materialized` instance that I get out of rom-yesql does not have that method.

Is rom-yesql supposed to be compatible with rom-repository, or can it only be used as a relation?

**Comment by solnic** [comment]
@mrship I haven't made it work with repos yet, but we can do it in next release. I want all adapters to work with repos, FWIW :)

**Comment by solnic** [comment]
This seems outdated, closing
