### ISSUE TITLE
Incompatible with rom-sql v1

### ISSUE THREAD

**Issue by gmartsenkov** [rom-rb/rom-yesql#12]
Hi there, i can't get `rom-yesql` to work with `rom 1.0` :(
Am i missing something or is it not supported yet?

- gemspec
```
spec.add_runtime_dependency 'sequel', '~> 4.40'
spec.add_runtime_dependency "rom-sql", "~> 1.0"
spec.add_runtime_dependency "rom-yesql", "~> 0.3.0"
spec.add_runtime_dependency "rom-repository", "~> 1.0.1"
```
- output
```
Bundler could not find compatible versions for gem "rom":
  In Gemfile:
    myapp was resolved to 0.1.375, which depends on
      rom-sql (~> 1.0) was resolved to 1.0.0, which depends on
        rom (~> 3.0)

    myapp was resolved to 0.1.375, which depends on
      rom-sql (~> 1.0) was resolved to 1.0.0, which depends on
        rom (~> 3.0)

    myapp was resolved to 0.1.375, which depends on
      rom-yesql (~> 0.3.0) was resolved to 0.3.0, which depends on
        rom (~> 2.0)
```

**Comment by flash-gordon** [comment]
@gmartsenkov Hi, I'd like to know whether you're really want to use ROM 1.0, not ROM 3.0 released recently?
As I can see `rom-yesql` has not been updated yet to be compatible with 3.0, so I'll have a look what needs to be done later today.

**Comment by gmartsenkov** [comment]
@flash-gordon my bad, i meant `rom-sql 1.0` which i assume depends on `rom 3.0`

**Comment by flash-gordon** [comment]
@gmartsenkov I managed to make it work with ROM 3.0. @solnic would you mind to release v0.4.0? As soon as you're able ;)

**Comment by solnic** [comment]
@gmartsenkov @flash-gordon just pushed rom-yesql 0.4.0

**Comment by gmartsenkov** [comment]
@flash-gordon @solnic you're awesome guys! thanks a lot
