### ISSUE TITLE
Upgrade to work with rom v4

### ISSUE THREAD

**Issue by mrship** [rom-rb/rom-yesql#14]
We are hoping to upgrade from rom 3 to 4 soon, but we have a hard dependency on rom-yesql. AFAIK this doesn't currently work with rom 4 - is it relatively easy to get it to work?

**Comment by solnic** [comment]
@mrship it should not be hard. I'll give it a shot later this week and hopefully we'll have a new release.

**Comment by mrship** [comment]
@solnic We are now looking to re-write our app and that would mean using Rom v5! We still have the dependency on rom-yesql though (which has worked out really well for us in the past). Is it likely easier to migrate to rom5? is there anything we can do to help move this along? 

thanks in advance for any tips/help

**Comment by solnic** [comment]
@mrship awesome :) it should be quite simple to upgrade this adapter to rom 5.0! feel free to give it a shot. You can open a draft PR if you get stuck and I'll help you out.

**Comment by citizen428** [comment]
@solnic Any pointers for someone who's willing to help with upgrading this to ROM 5 but isn't overly familiar with ROM internals yet? 

So far I forked, updated dependencies, made some Rubocop changes to be up to date with the current rules, but have had no luck getting the integration specs to pass (the unit ones are still green).

Initially it complains about a missing schema, but adding an inferred one leads to a `LocalJumpError` that seems to originate [here](https://github.com/rom-rb/rom/blob/c8c070a79c9f90483957452cb48567e9a2d9120a/lib/rom/setup/finalize/finalize_relations.rb#L103).

I'll keep digging by myself, but if you have any pointers I'd appreciate them 😃

**Comment by solnic** [comment]
@citizen428 a good starting point would be opening a draft PR. Then I could take a look and it'd be easier for me to provide feedback. Schemas are now mandatory so if a given adapter cannot infer them, you just have to provide them manually. Notice that rom-sql adapter ships with a schema inferrer.

**Comment by mrship** [comment]
Hi, I too got this far, but it appears that the definition of the `dataset` method in the `Yesql::Relation::ClassInterface` is not what ROM v5 expects - is this now expected to be a `Proc`?

```
wrong argument type Object (expected Proc)
./vendor/bundle/ruby/2.6.0/gems/rom-core-5.2.3/lib/rom/setup/finalize/finalize_relations.rb:99:in `build_relation'
```

To be frank, it is not simple to work out what has changed between ROM v3 and v5, but I'll keep playing and see if I can get any further.

**Comment by mrship** [comment]
I've opened #15 that at least gets a 💚 test suite. As I mentioned in the PR, I'm sure there is plenty of tidying up to do, but this is a first step at least. cc @solnic
